"""empty message

Revision ID: f237d9cd37de
Revises: faaedc3235d6
Create Date: 2021-11-18 22:38:49.564581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f237d9cd37de'
down_revision = 'faaedc3235d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=128), nullable=False),
    sa.Column('loser', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=128), nullable=False),
    sa.Column('loser', sa.String(length=128), nullable=False),
    sa.Column('winner_score', sa.Integer(), nullable=False),
    sa.Column('loser_score', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams_games',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'team_id')
    op.drop_table('teams_games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('rounds')
    # ### end Alembic commands ###
